# Generated by Django 4.2.16 on 2024-11-19 09:57

from django.db import migrations, models

def migrate_isbn_data(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    db_alias = schema_editor.connection.alias
    # Copy the old id value to the new isbn field
    Book.objects.using(db_alias).all().update(isbn=models.F('id'))

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_import_record_alter_book_unique_together'),
    ]

    operations = [
        # First add the new isbn field
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, null=True),
        ),
        # Copy data from id to isbn
        migrations.RunPython(migrate_isbn_data),
        # Make isbn non-nullable
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20),
        ),
        # Change id to BigAutoField
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        # Update unique constraint
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('isbn', 'import_record')},
        ),
    ]
